### ISSUE TITLE
TimeOut error when running script

### ISSUE THREAD

**Issue by wendallsan** [adimango/insights-for-instagram-scraper#1]
When I run the script, I get the following: 
```
 [path\to]\insights-for-instagram-scraper> node .\index.js willsmith
√ Valid page found
- Scraping url: https://instagram.com/willsmith  
TimeoutError: waiting for function failed: timeout 30000ms exceeded
    at new WaitTask ([path\to]\insights-for-instagram-scraper\node_modules\puppeteer\lib\DOMWorld.js:554:28)
    at DOMWorld.waitForFunction ([path\to]\insights-for-instagram-scraper\node_modules\puppeteer\lib\DOMWorld.js:459:12)
    at Frame.waitForFunction ([path\to]\insights-for-instagram-scraper\node_modules\puppeteer\lib\FrameManager.js:636:28)
    at Page.waitForFunction ([path\to]\insights-for-instagram-scraper\node_modules\puppeteer\lib\Page.js:1098:29)    at Scrapy.load ([path\to]\insights-for-instagram-scraper\Scrapy.js:65:28)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Scrapy.evaluate ([path\to]\insights-for-instagram-scraper\Scrapy.js:43:26)
√ Scraped 0 posts
```

**Comment by wendallsan** [comment]
tired of seeing this in my list of open  issues, so closing it.
